kafka:
  producer:
    bootstrapServers: 192.168.179.52:9092
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    bootstrapServers: 192.168.179.52:9092
    groupId: training-iceberg
    enableAutoCommit: false
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    autoOffsetReset: latest
    autoCommitInterval: 3000