kafka:
  producer:
    bootstrapServers: 192.168.178.219:6667,192.168.178.220:6667
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    bootstrapServers: 192.168.178.219:6667,192.168.178.220:6667
    groupId: flink_trainning
    enableAutoCommit: true
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    autoOffsetReset: latest
    autoCommitInterval: 3000