kafka:
  producer:
    bootstrapServers: kafka-pre:6667,atlas01:6667
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    bootstrapServers: kafka-pre:6667,atlas01:6667
    groupId: flink_trainning
    enableAutoCommit: true
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    autoOffsetReset: latest
    autoCommitInterval: 3000