kafka:
  producer:
    bootstrapServers: 172.21.64.139:9092
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    bootstrapServers: 172.21.64.139:9092
    groupId: flink_trainning
    enableAutoCommit: true
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.apache.kafka.common.serialization.StringSerializer
    autoOffsetReset: latest
    autoCommitInterval: 3000